* Papers Read

** May 2020

*** [[https://sites.ualberta.ca/~francisp/Phil428.526/UrquhartPost.pdf][Emil Post – Alasdair Urquhart (2008)]]

** June 2020

*** [[http://www.columbia.edu/%7Eav72/papers/JANCL_2003.pdf][Geometry of Negation (2003)]]

*** [[https://archive.org/details/jstor-27900610][Image of Creation (1916)]]

** July 2020

*** [[https://www.maa.org/press/periodicals/convergence/origins-of-boolean-algebra-in-the-logic-of-classes-george-boole-john-venn-and-c-s-peirce][Introduction article to Origins of Boolean Algebra in the logic of classes]]

*** [[http://www.commens.org/bibliography/journal_article/seibert-charles-h-2005-charles-peirce%E2%80%99s-reading-richard-whately%E2%80%99s][Charles Peirce’s Reading of Richard Whately’s Elements of Logic (2004)]]
Charles H. Seibert

Read 11 July 2020

*** [[https://www.jstor.org/stable/pdf/27900607.pdf][The Logical Work of Leibniz (1916)]]
Philip E. B. Jourdain
Read 12 July 2020

A good article briefing on the work of Leibniz. Need to trace the work of Jourdain further in logic.
He seems to be a regular author for Quarterly Journal of Mathematics.

*** [[https://www.jstor.org/stable/23940478][Leibniz and the Picture Theory of Language]]
William Kneale, 1966

- Parallels between the logical picture of Wittgenstein and Leibniz’s work is drawn.
- First order and second order natural signs are detailed.
- Poryphry’s exposition of Aristotle’s Categories and it finding a main audience in philosophy through the work of Boethius.
- Natural signs in the soul were called intentiones.
- Leibniz’ idea of costructing a scientific language that will form a thread of meditation (filum meditandi) is outlined.
- The idea that when a dyadical relation is introduced, the relationship modifying each of the two entities involved is detailed, that is the paternity of David to Solomon, grants Solomon the sonship of David.

** [[https://www.jstor.org/stable/2250689][Boole and the Revival of Logic]]
William Kneale, 1948

This is supposedly Kneale’s first work on the history of logic.

Read Part 1 out of 3. The rest two are expositions of his work, which I am deciding to read after perusing his work on logic.
Part 1 was a good read that shows the histiriographical works available on his life and his moral standings among other details on his life.

TODO: Read Part 2 and 3

** [[https://journals.openedition.org/philosophiascientiae/362?lang=en][H. MacColl and L. Carroll: Crosscurrents in geometry and logic]]

Describes the influence in Hugh MacColl’s thinking as he read and reviewed the work of Lewis Carroll. MacColl’s interest in logic was rekindled after 13 years when one of his friends sent him a copy of Symbolic Logic by Lewis Carroll. He described this in a letter to Bertrand Russell. In spite of some conflicting views, each modified their arguments to make them more clarified. Interesting read to know about how MacColl corresponded with Carroll by reviewing his books for The Atheneum publication.

Read 18 July 2020

** [[https://academic.oup.com/monist/article-abstract/21/4/564/2473154][Some Modern Advances in Logic]]
2 pages

A quick read on what advances where made by Frege, Peano, and Russell. Parallel is drawn between Euclid’s axioms and how modern logic differs from it. Empirical accent of the modern logic is stressed.

** [[https://academic.oup.com/monist/article-abstract/29/3/450/2335466][The Logical Significance of ”Okham’s Razor”]]
2 pages

Read 18 July 2020

Attention is drawn to the idea that making a parsimonious system of axioms following Okham’s dictum, is similar to having a least number of dependent variables in a linear system of equations as in the arithmetic.

** [[https://academic.oup.com/monist/article-abstract/25/4/633/2473106?redirectedFrom=fulltext][Mathematicians and Philosophers]]
P. E. B. Jourdain (1915)
6 pages

Details about the work of Berkeley that criticizes Newton, Hegel, and Kant and draws parallels between how then modern day (20th century) mathematics has surpassed these criticisms.

Read 19 July 2020

** [[https://academic.oup.com/monist/article-abstract/22/1/149/1021477][Mr. Bertrand Russell’s first work on the principles of mathematics]]
P. E. B. Jourdain (1912)
9 pages

A good read on the work of Russell and how he unified the work of Frege and Peano by using the logic of relations.

There are also interesting historical details and mathematical philosophical details that shine light on the evolution of formalism and work on Russell.

Read 19 July 2020

** [[https://www.tandfonline.com/doi/abs/10.1080/01445348408837059][Richard Whately and the Rise of Modern Logic]]

Read 22 July 2020

Describes how Whately’s work was distinct from others of the period. Draws attention to the work of Aldrich’s work and it acted as the primary reference point for departure for Whately.

The social context is described in which there was a force against diminishing the value of scholastic logic was ongoing and Whately’s work as one which places logic on solid foundations by clearly forming a course of work attempting to delineate it’s subject of discourse. Author also describes how mischaracterization of logic’s value prior to Whately’s work was leading to it’s perception as having diminished value in education.

The idea here that logic was part of humanities at Oxford is a significant point. Against the criticism of Playfair, Copleston defended that logic was neither an art nor a way to gain knowledge, thus dissociating it from Llull’s tradition of Ars Magna and Epistemology. He contented that Playfair had objected to a  a mistaken concept of logic.

Whately brought both algebra, and language closer to logic. He explictly draws an analogy between the letters he employed for the moods of the syllogistic with that of ones used in algebra.

The nominalistic approach in the works of Hobbes is outlined as an earlier precursor to the nominalistic approach of Whately. In my research, I was able to trace this thread going through C.I. Lewis to influence Post to Rosenbloom to Chomsky.

According to Van Evra, the distinction between the substative theory of reasoning and logic is that between a model and theory. Logic in Evra’s view to Whatley was the formal theory of theory of reasoning.

Details are also drawn to the common origin of mistakenly treating both induction as a form of argument and syllogism as a kind of argument. Though I didn't fully understand this subtlety.

The paper squarely locates Whately as the pioneering figure in influencing later developments in modern logic and wants to group him together with modern logic rather than among the scholastics which is what modern histories of logic tend to group him under.

** [[https://www.jstor.org/stable/10.1525/rh.1987.5.2.163][Richard Whately and the Revival of Logic in Nineteenth-Century England (1987)]]

Read 22 July 2020

Details about the historical context in which Richard Whately’s book emerged.
Precedents to the nominalist take in Whately’s work is linked to John Gillies translation of Aristotle and Richard Kirwan’s Logick.

Towards the end of the paper McKerrow also, draws attention to the idea that the two books of Whatley on rhetoric and logic acts as two sides of a coin.

A good description of how Whatley proscribed the limits of logic in his nominalist interpretation is given.

McKerrow also compares the innovation of Whatley to that of Stephen Toulmin’s Uses of Argument (1958) and The New Rhetoric of Chaïm Perelman and Lucie Olbrechts-Tyteca (1969)

** [[https://link.springer.com/chapter/10.1007/11780342_59][Gödel and Computability Theory]]
Richard Zach (2006)
Read 13 January 2021

Short read on the links between ideas of Gödel and Computability and Complexity Theory
** On Process

*** Conceptual Roots of Mathematics
