* Papers Read

** May 2020

*** [[https://sites.ualberta.ca/~francisp/Phil428.526/UrquhartPost.pdf][Emil Post – Alasdair Urquhart (2008)]]

** June 2020

*** [[http://www.columbia.edu/%7Eav72/papers/JANCL_2003.pdf][Geometry of Negation (2003)]]

*** [[https://archive.org/details/jstor-27900610][Image of Creation (1916)]]

** July 2020

*** [[https://www.maa.org/press/periodicals/convergence/origins-of-boolean-algebra-in-the-logic-of-classes-george-boole-john-venn-and-c-s-peirce][Introduction article to Origins of Boolean Algebra in the logic of classes]]

*** [[http://www.commens.org/bibliography/journal_article/seibert-charles-h-2005-charles-peirce%E2%80%99s-reading-richard-whately%E2%80%99s][Charles Peirce’s Reading of Richard Whately’s Elements of Logic (2004)]]
Charles H. Seibert

Read 11 July 2020

*** [[https://www.jstor.org/stable/pdf/27900607.pdf][The Logical Work of Leibniz (1916)]]
Philip E. B. Jourdain
Read 12 July 2020

A good article briefing on the work of Leibniz. Need to trace the work of Jourdain further in logic.
He seems to be a regular author for Quarterly Journal of Mathematics.

*** [[https://www.jstor.org/stable/23940478][Leibniz and the Picture Theory of Language]]
William Kneale, 1966

- Parallels between the logical picture of Wittgenstein and Leibniz’s work is drawn.
- First order and second order natural signs are detailed.
- Poryphry’s exposition of Aristotle’s Categories and it finding a main audience in philosophy through the work of Boethius.
- Natural signs in the soul were called intentiones.
- Leibniz’ idea of costructing a scientific language that will form a thread of meditation (filum meditandi) is outlined.
- The idea that when a dyadical relation is introduced, the relationship modifying each of the two entities involved is detailed, that is the paternity of David to Solomon, grants Solomon the sonship of David.

** [[https://www.jstor.org/stable/2250689][Boole and the Revival of Logic]]
William Kneale, 1948

This is supposedly Kneale’s first work on the history of logic.

Read Part 1 out of 3. The rest two are expositions of his work, which I am deciding to read after perusing his work on logic.
Part 1 was a good read that shows the histiriographical works available on his life and his moral standings among other details on his life.

TODO: Read Part 2 and 3

** [[https://journals.openedition.org/philosophiascientiae/362?lang=en][H. MacColl and L. Carroll: Crosscurrents in geometry and logic]]

Describes the influence in Hugh MacColl’s thinking as he read and reviewed the work of Lewis Carroll. MacColl’s interest in logic was rekindled after 13 years when one of his friends sent him a copy of Symbolic Logic by Lewis Carroll. He described this in a letter to Bertrand Russell. In spite of some conflicting views, each modified their arguments to make them more clarified. Interesting read to know about how MacColl corresponded with Carroll by reviewing his books for The Atheneum publication.

Read 18 July 2020

** [[https://academic.oup.com/monist/article-abstract/21/4/564/2473154][Some Modern Advances in Logic]]
2 pages

A quick read on what advances where made by Frege, Peano, and Russell. Parallel is drawn between Euclid’s axioms and how modern logic differs from it. Empirical accent of the modern logic is stressed.

** [[https://academic.oup.com/monist/article-abstract/29/3/450/2335466][The Logical Significance of “Okham’s Razor”]]
2 pages

Read 18 July 2020

Attention is drawn to the idea that making a parsimonious system of axioms following Okham’s dictum, is similar to having a least number of dependent variables in a linear system of equations as in the arithmetic.

** [[https://academic.oup.com/monist/article-abstract/25/4/633/2473106?redirectedFrom=fulltext][Mathematicians and Philosophers]]
P. E. B. Jourdain (1915)
6 pages

Details about the work of Berkeley that criticizes Newton, Hegel, and Kant and draws parallels between how then modern day (20th century) mathematics has surpassed these criticisms.

Read 19 July 2020

** [[https://academic.oup.com/monist/article-abstract/22/1/149/1021477][Mr. Bertrand Russell’s first work on the principles of mathematics]]
P. E. B. Jourdain (1912)
9 pages

A good read on the work of Russell and how he unified the work of Frege and Peano by using the logic of relations.

There are also interesting historical details and mathematical philosophical details that shine light on the evolution of formalism and work on Russell.

Read 19 July 2020

** [[https://www.tandfonline.com/doi/abs/10.1080/01445348408837059][Richard Whately and the Rise of Modern Logic]]

Read 22 July 2020

Describes how Whately’s work was distinct from others of the period. Draws attention to the work of Aldrich’s work and it acted as the primary reference point for departure for Whately.

The social context is described in which there was a force against diminishing the value of scholastic logic was ongoing and Whately’s work as one which places logic on solid foundations by clearly forming a course of work attempting to delineate it’s subject of discourse. Author also describes how mischaracterization of logic’s value prior to Whately’s work was leading to it’s perception as having diminished value in education.

The idea here that logic was part of humanities at Oxford is a significant point. Against the criticism of Playfair, Copleston defended that logic was neither an art nor a way to gain knowledge, thus dissociating it from Llull’s tradition of Ars Magna and Epistemology. He contented that Playfair had objected to a  a mistaken concept of logic.

Whately brought both algebra, and language closer to logic. He explictly draws an analogy between the letters he employed for the moods of the syllogistic with that of ones used in algebra.

The nominalistic approach in the works of Hobbes is outlined as an earlier precursor to the nominalistic approach of Whately. In my research, I was able to trace this thread going through C.I. Lewis to influence Post to Rosenbloom to Chomsky.

According to Van Evra, the distinction between the substative theory of reasoning and logic is that between a model and theory. Logic in Evra’s view to Whatley was the formal theory of theory of reasoning.

Details are also drawn to the common origin of mistakenly treating both induction as a form of argument and syllogism as a kind of argument. Though I didn't fully understand this subtlety.

The paper squarely locates Whately as the pioneering figure in influencing later developments in modern logic and wants to group him together with modern logic rather than among the scholastics which is what modern histories of logic tend to group him under.

** [[https://www.jstor.org/stable/10.1525/rh.1987.5.2.163][Richard Whately and the Revival of Logic in Nineteenth-Century England (1987)]]

Read 22 July 2020

Details about the historical context in which Richard Whately’s book emerged.
Precedents to the nominalist take in Whately’s work is linked to John Gillies translation of Aristotle and Richard Kirwan’s Logick.

Towards the end of the paper McKerrow also, draws attention to the idea that the two books of Whatley on rhetoric and logic acts as two sides of a coin.

A good description of how Whatley proscribed the limits of logic in his nominalist interpretation is given.

McKerrow also compares the innovation of Whatley to that of Stephen Toulmin’s Uses of Argument (1958) and The New Rhetoric of Chaïm Perelman and Lucie Olbrechts-Tyteca (1969)

** [[https://link.springer.com/chapter/10.1007/11780342_59][Gödel and Computability Theory]]
Richard Zach (2006)
Read 13 January 2021

Short read on the links between ideas of Gödel and Computability and Complexity Theory

** [[https://www.vordenker.de/ggphilosophy/mcculloch_what-is-a-number.pdf][What is a number, that a man may know it, and a man, that he may know a number?]]
Warren McCulloch
Read 5 February 2021

A nice read on the life and work of McCulloch. Assumes a good knowledge of the history of logic and the role played by the recent innovations since Charles Peirce. There are some parts about probabilistic logic that I couldn't quite follow. Would need immersal in the work of McCulloch to learn to work with it.

** [[https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.92.2244&rep=rep1&type=pdf][Calculus Ratiocinator vs. Characteristica Universalis? The Two Traditions in Logic, Revisited]]
Volker Peckhaus
Read 7 February 2021

A really good paper that outlines how the two themes in the work of Leibniz: Calculus ratiocinator and Characteristica Universalis went on to influence later developments in the 19th and 20th century.

Author goes on to differentiate between two schools of logic: the algebraic school and the mathematical logic school. The question involves the usefulness of algebra in the actual shape of logic. People like Arthur Prior, Michael Dummett, and W. V. O. Quine are evidenced as people who challenged the primacy of algebraic school of logic.

Quine locates the idea of quantification theory as the emergence of logic as a substantial branch of mathematics.

Works of Jean van Heijenoort (1976b) of dividing “logic as calculus” and “logic as language” is cited. This is said to be developed by the work of Jaakko Hintikka to “languages as caluculs” and “language as a universal medium”.

The two ideas are not disjunctive but rather have overlaps in that Frege himself notes that the inferring calculations as a necessary component of a concept script. The concept script as per Peckhaus was meant to emphasize the lingua characterica aspect of logic.

With quantification theory acting as the central powerhorse, lingua characterica is considered by Heijenoort to constitute a language powerful enough perhaps to represent all of scientific knowledge.

Algebraic calculus uses model-theoretic approach where interpretations of operations and categories (classes of concepts) are needed. They can be divided into a structural/syntactic and a semantic side. The latter providing interpretation of the figures used.

The main features of Fregean system is identified as: quantification, universality, internal semantics, a closed/fixed universe of discourse.

Leibniz envisioned an ars characteristica which will represent letters according to the models of mathematics and the notation allows for calculating with concepts according to a set of rules. It allows for mechanically deducing all possible truths from the list of simple thoughts. Characteristic is responsible for the semantic part and calculus ratiocinator forms the syntact part of the lingua rationalis.

In the initial period of partial realizations of this program, the systems of characters allow various interprations. In the final (utopian) stage after having reached at the complete designation of all possible simple thoughts, the system would be categorical in nature.

Peckhaus locates the idea of Schröder with an external semantics to be more close to the Leibnizian idea of lingua rationalis.

The article comes to a close by showing how Schröder was influenced by the work of Charles Peirce and his student Oscar Howard Mitchell in creating his own style of quantification in the algebraic school which is close to infinitary logic. Peckhaus uses this idea to underline that quantification theory cannot be taken to be the distinguishing factor for the two traditions in the history of logic

** [[http://www.blackwellpublishing.com/content/BPL_Images/Content_Store/WWW_Content/9780631216711/003.pdf][The Rise of Modern Logic]]
Rolf George and James Vans Evra

Read 17 February 2021

A tapestry of logical systems as having dominated before the first half of 20th century.

The book starts with the work of Peter Ramus which identified Dialectic with Logic and which lead to logic to be understood as art of rhetoric and disputation. This therefore, lead to the works in philosophy and literature not advancing or concerning themselves with the subject much.

Francis Bacon, Descartes, and John Locke is said to have hold the opinion that scholastic logic as holding us back from the inquiry into truth. Hume continued Locke’s attack and (one of ?) the most widely read work of that period article in Encylcopédie by Denis Diderot also bashed logic.

Gottfried Wilhelm Leibniz was the great exception to this. In his correspondence with Locke, latter’s representative Philateles eventually admits as being able to percieve logic as universal mathematics.

Theory of terms or concepts, their combination into judgements, and the composition of syllogisms from judegments. (Roughly: Primitives -> Interpretive statements -> Structures).

The elucidation of the structure of logic was prefaced by a discussion of some epistemological preliminaries: the origin of concepts as inherent in the mind or deriving from sensation and perception. The authors claim that inorder for logic to take the shape of modern logical theory.

Kant and Whately are said to be the prime movers who played a role in eliminating some material and reorienting logic towards its modern conception.

Kant changed his mind from Locke’s book de intellectu is the ground of all true logica to Locke “speaks of the origin of concepts, but this really does not belong to logic”. While claiming earlier that the logician must know the human soul and cannot proceed without psychology, he now held that “pure logic derives nothing from psychology”.

Organon: Attemps to codify methods of discovery.
Canon: A method of evaluation of the discoveries

He held that there is no universal method of discovery and logic to be catering only to form and not to content, and that it can only be a canon (diiudicatio).

He divide logic into theory and practice. This practice was associated with the skill of reasoning and disputation while logic proper as a theoretical inquiry.

Richard Whately posited that the ground for discourse of logic is like objective sciences Chemistry or Mathematics in that its point is the enunciation of principle apart from application.

For Richard Whately logic was not an engine of discover or “an aart of rightly employing rational faculaties” but was an inquiry into the formal structures. He considered logic to be about lanugage rather than valuely considered “thought”.

Whately is said to have given logic the characteristic form. He eliminated some assocations and gave it a precise definition making it closer to how grammar is to language.

Syllogisms : Articulated Argument :: Grammar : Language

Bernard Bolzano wrote Theory of Science (Wissenschaftslehre) in 1837.

Introduced the idea of the content which is  asserted or denied by a proposition is a ‘proposition in itself’.

Propositions are introduced first and any component of a proposition that is not a proposition itself is a Vorstellung (idea or representation ; sounds like an atompic component / primitive in modern parlance).

Bolzano noted that no one had successfully defined the type of combination of terms that generates a proposition. Several of the attempts he examined did not distinguish propositions from complex terms and others defined it in terms of “acts of the mind”, “contaminating” logic with psychology.

Hobbes and Condillac identified propositions with equations. They further maintained that the principle on which all syllogisms rest is that two things equal to a third are equal to each other.

But Bolzano notes that while all equations are propositions, not all propositions are equations and paid no further attention to this doctrine.

Identifying propositions with equations demanded adjustments like the quantification of the predicate. Ploucquet thought that in an affirmative proposition the predicate cannot be different from the subjects: All lions are animals as All lions are some animals.
All X are Y as All of X = Part of Y (George Bentham on a commentary to Whately’s book)
This doctrine is usually associated with the name of William Hamilton who gave it wider currency.

Bolzano contributed the idea of logical consequence using the mathematical technique of substitution on variables.

The unusual triadic construction of consequence also allows for enthymemes or partly ‘material’ consequences, where only a subset of extralogical terms is varied.

Laws of thought: Identity, Contradition, and Excluded Middle

Bolzano agreed that these principles are true. Logic he maintained, objeys these laws, but they are not its first principles (or axioms in modern parlance).

Bolzano took mathematics to be a purely conceptual science and disagreed with Kant’s view that it was founded on intuition.

John Stuart Mill attacked logic claiming that formal principles, especially the syllogism, are a petitio principii since they can generate no new knowledge.

Mill claimed that the truths of geometry and arithmetic are empirically discovered by the simplest inductive method, that is enumeration.

Mill took the empiricism and psychological approach to logic, whose “theoretic grounds are wholly borrowed from psychology, and included as much of that science as is required to justify the rules of the logical art”. This holds in particular for the “laws of thought”, which are grounded either in our psychological constitution, or in universal experience.

System of Logic by Mill is best known for formulating rules for the discovery of the causes, his famous ‘canon’: the methods of agreement, difference, residues, and concomitant variation. Popularity of this text in England lend support to the view that logic is methodology and the art of discovery.

Logic was turned into a strong branch of mathematics under the expertise of George Boole, not of philosophy. This would excise methodology, rhetoric, and epistemology. Logic was cast in a symbolic language.

Syllogisms can now be calculated by using arithmetic, specifically by maneuvering the middle term into a position where it can be eliminated. Syllogistics becomes part of the algebra of classes and thus an area of mathematics. If every argument can be formulated as a syllogism, then all of logic is a part of algebra.

Short comings of Boole’s rendition:

Existential propositions where represented as v = xy where v stands for a non-empty class. But how can one define such a class?

His logic was a logic of terms

Recognition of negation came only later in the century

Changing the status of standard copular — is — Augustus De Morgan showed how the bounds of categorical statements could be widened into the realm of relational statements.

”Every man is an animal. Therefore the head of a man is the head of an animal” cannot be accomodated in traditional syllogistic logic.

De Morgan introduced the concept of “universe of discourse”, which targeted statemetns to a class of objects under discussion rather than the entire universe.

Charles Sanders Peirce first thought logic to be part of semiotics, but then took it to be that theory, and while talking logic to be descriptive first, he later thought it to address cognitive norms.

Gottlob Frege attempted to derive arithmetic from logical concepts.

In his work, a function symbol refers to / denotes a concept, the name/argument an object. Concepts and objects belong to distinct ontological categories. When a concept term is an argument in a sentence, the sentence is said to be on a higher level than those whose arguments refer to objects.

Conceptual structures are used to determine if certain configurations “fall under” them. For a concept: () is a planet, the object Merccury, when substituted in the structure gives Mercury is a planet which is said to map to true and hence to fall under the structure while Sirius is a planet fails to and doesn't fall under it.

Another profound innovation of Frege was the quantifier. In mathematics, quantification is usually tacit: x + 0 = x, means that for all x, it is a true identity. Wherease to denote the opposite of it, one can say x + 0 != x, but for cases where “Not everything is F” cannot be done so and for that a special sign, a quantifier with a scope is needed. This allows to distinguish between:

not(ForAll(x, F(x))) : Not everything is F(x)
ForAll(x, not(F(x))) : Everything is not(F(x))

Frege took quantifiers to be higher level functions. There is a planet was translated as There is at least one thing such that [() is a planet]. The quantifier here is constructed as a function that has another function as its argument.

Frege emphasized the importance of the deductive method. Claims in a deductive science must be justified by a proof which is a sequence of propositions, each of which is either an assumption, or follows from previous members of the sequence by clearly articulated steps of deduction.

With this understanding of the structure of propositions, of quantification, and of the nature of a proof. Begriffsschrift develops an axiomatic system of sentential logic, based on two sets of axioms: one on conditionals and the other on negation.

The rule of modus ponens is employed to generate the first consistent and complete system (proved later) system of sentential logic.

A third principle, substitutivity, is introduced: if a = b, then F(a) is equivalent (as we now say) to F(b). With the introduction of a fourth principle, now ‘universal instantiation’ or ForAll-elimination, a system of second order predicate logic is developed.

Substitutivity fails in so-called oblique/opaque contexts. According to Frege, they are dependent clauses introduced by words as ‘to say’, ‘to hear’, ‘to believe’, ‘to be convinced’, ‘to conclude’ and the like.

‘N believes that the morning star is a planet’ may be true while ‘N believes that the evening star is a planet’ false even though the two heavely bodies are identical violating the principle of substitutivity.

To save this principle, Frege introduced sense (sinn) and reference (Bedeutung).

Morning star and evening star may refer to the same object, but they have a different sense.

In opaque contexts such expressions do not name an object, but their own sense, allowing substitution with any name of identical sense.

Sentences in oblique contexts have as their reference not their truth value, but the thought or sense they express. In this way, substitutivity, for Frege an incontrovertible principle of logic, can be made to work in opaque contexts.

In Foundations of Arithmetic, Frege attempted to define the sense of a sentence in which a number word occurs. This is associated with the ‘linguistic turn’ foreshadowing and inspiring 20th century analytic philosophy: the question how we come to know numbers is transformed into one about the meaning of sentences in which number words occur.

Context principle: Only in the context of a sentence does a word have meaning.

Hume’s Principle: “When two numbers are so combined as that the one has always a unit answering to every unit of the other, we pronunce them equal”

Fifth principle: Unrestricted comprehension (or abstraction) axiom.

Bertrand Russell’s discovery showed that the axioms of arithmetic (now commonly stated in the form Guiseppe Peano gave them) cannot be formally and consistently derived from Frege’s principles. Only  in recent years has it been shown that these axioms follow from the principles of logic (minus the ill-fated Fifth) together with Hume’s Principle. This is now called ‘Frege’s Theorem.’

Franz Brentano observed that all ‘psychological phenomena’ are targeted on some object: when we think, we think of something. These are intentional objects whose existence or nonexistence need not be an issue.

Brentano shied away from allowing the contents of mental acts to have a form of being as this is to be an unseemly Platonism.

His students Kasimir Twardowksi and Edmund Husserl distinguished content from object with the object determined by the content. This is analogues to sense and reference.

Students of Twardowski formed the school of Polish logicians. Lesniewsky was one of them who explored mereology.

Mereology is different from set theor in that an element of a class is not a part of it, though a subset is. Importantly, membership is not transitive: if elementOf(s, t) and elementOf(t, u), then s is not an element of u whereas a part of a part is a part of the whole.

Alexius Meinong, another of Brentano’s students inquired into the nature of intentional acts that lack existing objects and are ‘beyond being and non-being.’

He is credited with inpsiring free logic.

Bertrand Russel gave a distinction between proper names and expressions which he titled definite descriptions.

The present king of France is bald was analyzed into:

1) location(atLeast(King, 1), France)
2) location(atMost(King, 1), France)
3) isBald(King, True)

Now each of these condition can be violated giving no king, more than one king and non-bald king.

This logical phrasing style is evidenced to convey the idea that there’s misleading ‘surface structure’ of the sentence which disguises the logical structure.

I feel the idea of ‘present king’ in the temporal aspect is elevated to an eternal status here.

Russell concludes that definite descriptions are not names, as Frege had thought. If so, then they would lead to ontological “excesses” as posited by Meinong.

Natural language structure and grammar are misleading and must be distinguished from the deeper logical structure. This is said to have lead philosophers to argue that metaphysical and political convictions often gain their plausibility from deceptive natural language expressions.

Expressions like definite description, but not only they, can be defined only in their contexts, by definitions in use.

Russell held that logicism could be made to work if the comprehension axiom were restricted. He proposed several solution,s eventually the theory of types, through which Frege’s contributions entered the mainstream of logic.

The theory of types stratifies expressions in a hierarchical order so that elements of a set are on a lower level than the set, making it impossible for a set to be a member of itself. A ‘ramified’ theory of types is introduced to solve as well the so-called semantic paradoxes like the liar paradox.

Type theory is said to have the burden of having to recognize a separate definition for truth at each type level and the inability to define a number as the set of all similar (2 membered, 3 membered etc.) sets. They resolve this by using symbols that are ‘systematically ambiguous’ between types.

Russell and Whitehead did succed in deriving a significant portion of mathematics from their principles: a comprehensive theory of relations and order, Cantor’s set theory, and a large portion of (finite and transfinite) arithmetic.

Principia was meant to be a kind of Lingua Universalis, a canonical language pure enough to permit construction of disciplined discourse on the skeleton it provided.

In summary, several distinct areas of study were advanced under the name of logic:

- As an investigation on cognitive performence/scientific methodology
- Strategy of discovery
- Branch of rhetoric

Including these, there were two distinct types of theory: syntactical / proof theory and semantic definition of logical consequence, which does not dwell on the process of derivation.

The most important development of logic after Principia was to bring these two strands together. In propositional logic, for instance, truth tables (introduced by Wittgenstein in 1922) allow a semantic test for the validity of formulas and proofs, a continuation of Bolzano’s project. It was then proved that the Principia version of propositional logic is complete, that is to say that every semantically valid formula can be derived in it and that it is consistent, that is only such formulas (and hence no contradiction) can be derived. Kurt Gödel later proved that first order predicate logic is complete as well, but that higher order logic is not. Since the latter is needed to define arithmetic concepts, it is said that this spelled the end of the logicist project.

** On Process

*** Conceptual Roots of Mathematics
