* History of Logic

A repo that keeps track of the history of logic. It chronicles the eminent personalities, schools of thought, ideas of each epoch.

* Ancient Logic

* Classical Period

The period roughly between 8th century B.C. to 6th century A.D

* Early Greeks

* Parmenides

* Zeno of Elea

Argumentation had methods that resembled reduction ad absurdum

A/this if B/that. But B/that is impossible, hence A/this is impossible.

* Epimenides

* Sophists

* Gorgias

* Hippias

* Prodicus

* Protagoras (490 – 420 B.C.)
Distinguished between wish, question, answer, and command

* Hippocrates (460 – 370 B.C.)
Attempt at formulating principles of scientific research. This is said to be related to logic of induction.

* Alcidamas (~4th Century B.C.)
Pupil of Gorgias

Distinguished between phasis (assertion) and apophasis (denial), and question and address (prosagoreusis)

* Antisthenes (446 – 366 B.C.)
Defined a sentence as that which indicates a thing was or is.

* Dissoi Logoi (~400 B.C.)
Also known as Dialexis.

Book of unknown authorship

Perhaps the earliest surviving piece of logical arguments.
One of the key themes of the book seems to be that in order to act, one must be persuaded to choose one side or the other.
This process is said to be accomplished through dissoid logoi

The book is also said to be one of the primary records that shows the awareness that self-reflexive/self-referential use of the truth predicate can be problematic as seen in Liar’s paradox.

* Socrates

* Plato (428/27/24/23 – 348/47 B.C)

Distinguished between syntax (What is a statement?) and semantics (When is it true?).

Something was considered to be a statement when it specifies a subject and says something about it. That is in other words, both the onoma and rhema (or subject and predicate) are present. Statements with empty subject-predicate relationships are excluded as statements.

Plato is said to have produced a deflationist theory of truth by saying that when a statement is true when it says what is and false when it is not (Theatetus is flying).

Negation is said to have a narrower scope than affirmation in that negation negates the predicate not whole sentences.

Plato is said to have grappled with the ideas of multiple meanings of the word ‘is’:
1/ to represent being (Example: There is a ball)
2/ to represent equality (Archytas is the King of Greece)

Think ‘is’ can have one more which is predication (The ball is red)

He is also said to have anticipated the law of non-contradiction

Deepening the studies on the structure of argumentation lead to reflection upon patterns of argumentation. Valid and invalid arguments were studied which resulted in identifying ways in which valid inferences can be made.

** Dialectic
Plato brought structure and rules to the argumentation that was conducted in antiquity.

** Sophist
Analyzes simple statement as containing verb (rhêma / ῥῆμα) which indicates the action and noun (onoma / ὄνομᾰ).

** Euthydemus

Contains a large number of paradoxes

* Aristotle (385 – 323 B.C.)

In Aristotle’s work, a subject (onoma) is linked to a verb (rhema), together which becomes a proposition (logos).

Initiated work on modal logic.

Deduction and proof developing in Greek mathematics is said to have influenced Aristotle (Verify/validate, how exactly he was influenced by it).

* Organon
*** Categories
This title means predications.
It can mean one of:
**** Substance (ousia)
**** Quantity (poson)
**** Quality (poion)
**** Relation (pros ti)
**** Location (pou)
**** Time (pote)
**** Position (keisthai)
**** Possession (echein)
**** Doing (poiein)
**** Undergoing (paschein)

*** De interpretatione

A declarative sentence (apophantikos logos) or declaration (apophansis) is different from other kinds of discourse like command or question. These can be judged for their truth value. They signify thoughts which are shared by humans and through these, indirectly, things. Written sentences signify spoken ones.

Subjects and predicates are connected by a copula.

Names can be singular terms or common nouns, both can be empty.
Singular terms can take subject position.
Verbs co-signify time.

A declarative sentence can be affirmed or negated depending on its predicate.

In terms of quantity, a sentence can be thought of as singular, particular, indefinite, universal.

Includes four forms of categorical statments:
Every S is P
No S is P
Some S is P
Some S is not P

And the relations between them

Based on this theory, he created the doctrine of the categorical syllogism, in Prior Analytics.

*** Prior Analytics

Contains variable letters A, B, C etc. to stand in place of terms
Develops the syllogistic as a system of deductive inference

By the theory of reduction, the syllogistic moods are shown to be interconnected so that all can ultimately be reduced to two: Barbara and Celarent.

*** Posterior Analytics
*** Topics
Books (2 – 7) about how to find procedures/rules (topoi) to find an argument to establish/refute a thesis.
4 kinds of relationship a predicate may have to subject known as predicables. It may grant it a:
**** Definition
**** Genus
**** Unique property
**** Accidental property

*** Sophistical Refutations
Systematical classification of logical fallacies
**** Equivocation
**** Secundum quid
**** Affirming the consequent
**** Begging the question

** Metaphysics Γ, Δ, Θ
** Poetics
** Rhetoric
** De Anima
** Syllogistic
** Enthymeme
** Existential import
Both universal and particular sentences contain a quantifier and both universal and particular affirmatives were taken to have existential import. This was not so the case for negations, as it is reflected in some of the work Sturm has done and Leibniz has said not to be in line with Aristotle’s work.

** Contraries and Contradictories
Contrary sentences cannot both be true
Contradictory of a universal affirmative is the corresponding particular negative and conversely, for the universal negative.

* Categories

* Classes

* Eudemus of Rhodes (370 – 300 B.C.)

* Theophrastus of Eresus (371 – 287 B.C.)

Student of Aristotle.

Made the theory of modal syllogisms consistent by peiorem rule

Developed a theory of wholly hypothetical syllogisms based on a prototype of syllogisms composed of three conditional propositions. He thought these were reducible to categorical syllogisms though the method is said to have not survived.

* Philo the Dilectician (300 B.C.)

* Megarians

Followers of Euclid of Megara

* Eubulides of Miletus
Pupil of Euclid of Megara

** Liar’s paradox

** Sorites paradox

* Diodorus Cronus (? – 284 B.C.)

* Philo of Megara (fl. 300 B.C.)
Gave a truth-functional definition of the connective ‘if…then…’

* Stoics

Systematized propositional logic inspired from Megarian logic.

Used variables where the propositions themselves were variables not terms.

And the signs employed for these were ordinal numbers (the first, the second) and not letters.

Their syllogistic was grounded on five types of indemonstrable arguments as basic syllogisms and four ground rules (themata). Using these, all other syllogisms were claimed to be reducible to these indemonstrables.

It is said to be independent of Aristotle’s term logic, but verify this claim.

* Zeno of Citium (336 – 265 B.C.)

* Epicureans
Developed a theory of inductive inference

* Chryssipus (279 – 206 B.C.)

* Galen, the physician (129 – 199 A.D.)

Tried to synthesize the logic of Stoics and Aristotle/Peripatetics

Said to have introduced relational syllogism

* Alexander of Aphrodisias (~ 200 A.D.)

Commentator on Aristotle

* Poryphry of Tyre (232-4 – 305-6 A.D.)

** Isagoge

* Ammonius Hermeiou

Commentator on Aristotle

* Marius Victorinus

* St. Augustine (354–430)

* Martianus Capella

* Boethius (480 – 524 A.D.)

* Simplicius

* John Philoponus (490 – 570  A.D.)

Commentator on Aristotle

* Sextus Empiricus

* Lucius Apuleius (124 – 170 A.D.)

** De philosophia rationali

* Diogenes Laërtius

Commentator

* Cicero

* Arabian Logic

* Abu Yūsuf Yaʻqūb ibn ʼIsḥāq aṣ-Ṣabbāḥ al-Kindī (805 – 873 A.D.)

* Abu Nasr al-Fārābī

* Abū Ḥāmid Muḥammad ibn Muḥammad aṭ-Ṭūsiyy al-Ġaz(z)ālīy / Al-Ghazali (1058 – 1111 A.D.)

* Abu Ali Sina / Avicenna (980 – 1037 A.D.)

* Abū l-Walīd Muḥammad Ibn ʾAḥmad Ibn Rušd / Ibn Rushd / Averroes (1126 – 1198 A.D.)

* Scholastic Logic

* Medieval Logic

Middle Ages are roughly the period between 6th century and 14th century

* Alucin of York (730 – 804 A.D.)

** Books surverying medieval logic

Medieval Foundations of the Western intellectual Tradition (1976)

Articulating Medieval Logic (2014)

* Garland, the Computist (~ 1040 A.D.)

* St. Anselm of Canterbury (1033 – 1109 A.D.)

* James of Venice

* Sophismata

* Syncategoremata

* Insolubilia

* Obligationes

* Terminist logic
Because they put emphasis on term logic

* Abbo of Fluery

* Garlandus Compostita

* Peter Abelard/Abailard (1079 – 1142)

* Adam Parvipontanus

* Gilbert of Poitiers (1080 – 1154)

* Alberic van Reims

* John of Salisbury (1120 – 1180)

* Modism

* Summulists

* Peter of Hispania/Spain (d. 1277)

** Summulae Logicales

* Lambert of Auxerre (13th Century)

** Summa Lamberti

* William of Sherwood (1200/1210? – 66/70/72)

** Introductiones in Logicam

* Robert Kilwardby (d. 1279)

* Albert the Great (1200–80)

* Roger Bacon (1215/19/20 – 1292/94)

* Boethius of Dacia (c. 1270)

* Henry of Ghent (c. 1217-93)

* Ralph Brito (c. 1290–1330)

* Siger of Kortrijk (d. 1341)

* Simon of Faversham (c. 1300)

* Thomas Aquinas (1224/25 - 1274)

* Thomas Aquinas (1225 – 1274)

* Ramon Llull (1232 – 1315)

* John Duns Scotus (1265/66 – 1308/9)

* Peter Aureoli (1280 – 1322)

Modality linked with time

* Pseudo Scotus (?)

* William of Ockham (1285 – 1347)

Developed theory of modality

* Walter Burley/Burleigh (1275 – 1344/5)

** De puritate artis logicae

* Robert Holkot (c. 1290 – 1349)

* William of Heytesbury (d. 1272/3)

* Gregory of Rimini (c. 1300 – 1358)

* John Pagus (13th Century)

* [[https://en.wikipedia.org/wiki/Supposition_theory][Supposition Theory]]

Took shape by 12th century, then neglected for a while until Burley in England and Buridan in France revived it in the 14th century.
Was the main vehicle for semantic analysis in the middle ages.

* William of Sherwood (1200 – 1272)

* Roger Bacon (1219/20 – 1292)

* Jean Buridan (1301 – 1359/62)

* Nicholas of Autrecourt (c. 1300 – after 1358)

* Richard Billingham (c. 1350–60)

* Albert of Saxony (1316/20 – 1390)

** Perutilis logica

* Marsilius of Inghen (1340 – 1396/99)

* Pierre d'Ailly (1351 – 1420)

** Conceptus et insolubilia (1372)

* Henry Hopton (~ 1357)

* Vincent Ferrer (c. 1350 – 1420)

* Peter of Ailly (1350–1420/1)

* John Wycliffe (1320/31 – 1384)

* Richard Lavenham (~ 1380, died > 1399)

* Ralph Strode (1350 – 1400)

* Richard Ferrybridge/Feribrigge (~ 1360)

* Paul of Venice (1369 – 1429)

** Logica parva
** Logica magna

* Paul of Pergola (1380 – 1455)

* Peter of Mantua (d. 1400)

* John Venator/Huntman/Hunter (~ 1373)

* Renaissance Logic

A trend as new renaissance logic emerges is the start of sustained tension and critique between new forms of logic and that of traditional scholastic logic. Certain schools such as Oxford (in the form of individuals like Aldrich, Whately) gives support to the traditional logic, while alternatives cast in the tradition of Cartesian and Lockean modes of epistemology begins to criticize syllogisms and a mutual dialogue between them can be seen in this period.

Nicholai Ivanovich Styazhkin identifies three main branches that spun off during Renaissance. The Traditional logic that remained conserved in religious institutions, reform logic of Melanchthon and Ramus, and mystical tradition beginning from Ramón Llull.

* Oxford Calculators

14th Century thinkers from Oxford Merton School

* Thomas Bradwardine (1300 – 1349)

* George of Trebizond / Georgius Trapezuntius (1395 – 1486)
Book on dialectic
Contains square of oppositions

* William of Heytesbury (1313 – 1372/1373)

* Richard Swineshead/Sussieth (~1340/1354)

* Martin Luther (1483 – 1546)

* Jakob Martini (1570 – 1649)

* Desiderius Erasmus (1466 – 1536)

* Philipp Melanchthon (1497 – 1560)

* Juan Luis Vives (1492 – 1540)
De censura veri et falsi

* Nicolaus Reimers (1551 – 1600)

* Bartholomäus Keckermann

** Systema Logicæ: Sompendiosa methodo
** Systema Logicæ: Tribus Libris Adornatvm

** Metamorphosis Logicae (1589)

* Petrus Ramus (1515 – 1572)

* Robert Sanderson (1587 – 1663)

** Logicae Artis Compendium (1615)

* Francis Bacon (1561 – 1626)

** Novum Organon (1620)

* Richard Crakanthorpe (1567 – 1624)

** Logicae libri quinque de Predicabilibus, Praedicamentis (1622)

* John Argall (1540 – 1606)

** Introductio ad artem Dialecticam (1605)

* Joachim Jung/Jungius/Junge (1587 – 1657)

** Logica Hamburgenis
Replacement for the Protestant logic of Melanchthon

** Oblique syllogisms

* François Viète (1540 – 1603)

** Character Universalis

* Johann Heinrich Alsted (1588 – 1638)

* René Descartes (1596 – 1650)

** Regulae ad directionem ingenii (Rules for the direction of the Mind) (1628)

** Mathesis Universalis

** George Dalgarno (1616 – 1687)

** Character Universalis

* John Wallis (1616 – 1703)

** Institutio Logicae (1687)

* Johannes Clauberg (1622 – 1665)

Known as a Scholastic Cartesian
Attempted to develop a Cartesian Logic

* Port–Royal Logic

Followed Ramus’ outline of concept, judgement, argument, and method. Had explicit distinction between comprehension and extension.

Influential discussion of definitions that was inspired byt he work of French mathematician and philosopher Blaise Pascal.

* Antoine Arnauld (1612 – 1694)

** La logique, ou l’art de penser (1662)

** Erhard Weigel (1625 – 1699)

* Pierre Nicole (1625 – 1695)

* Blaise Pascal (1623 - 1662)

* Arnold Geulinx (1624 – 1649)

** Logica fundamentis suis restituta (1662)
Tried to reinstitute the rich detail of scholastic logic

* John Locke (1632 – 1704)

** Essay concerning Human Understanding (1690)

** On the conduct of the understanding (1706)

* Johann C. Sturm (1635 – 1703)

** Universalia Euclidea. Accedunt ejusdem XII. Novi Syllogizandi Modi in propositionibus absolutis, cum XX. aliis in exclusivis, eâdem methodo Geometricâ demonstrates. Hagæ-Comitis (1661)

Used diagrams like Euler circles

* Christian Weise

* Samuel Grosser (1664 – 1736)

Pharus Intellectus, sive Logica electiva
Gründliche  Anweisung zur Logica

* Samuel Pufendorf

* Jacob Thomasius

* Johann C. Lange (1670 – 1744)

Extensively used Euler circles

** Nucleus Logicae Weisianae

700 page commentary on the Weise’s handbook of logic. These comments contain numerous diagrams.

* Johannes de Raey (1622 – 1702)

* Bartholomaeus Schimpffer

* Arch Deacon Jacob Ellrod

* Weigelius

** Philosophia Mathematica (1693)

** Idea Matheseos universae (1669)

* Gottfried Wilhelm Leibniz (1646 – 1716)

** De arte combinatoria (1666)

** Lingua Characteristica Universalis

** Calculus Ratiocinator

** De formæ logicæ comprobatione per linearum ductus

** De cogitationum analysi

Uses circle diagrams together with tree diagrams to represent the relation of concepts in jurisprudence.

* Johannes Hospinianus Steinanus (1515 – 1575)

* Henry Aldrich (1647 – 1710)

** Artis logicae compendium (1691)

* Jakob Bernoulli (1654 – 1705)

Published a work on parallels of logic and algebra.
Gave algebraic examples of categorical statements.

* Gerolamo Saccheri (1667 - 1733)

** Logica Demonstriva (1697)

* Isaac Watts (1674 – 1748)

* Christian Wolff (1679 – 1754)

* John Wesley (1703 – 1791)

Founder of Methodism

* Johann Andreas von Segner (1704 – 1777)

Was influenced by Wolff’s exposition of Leibniz

* Leonard Euler (1707 – 1783)

Introduced Euler circles

* Thomas Reid (1710 – 1796)

** A Brief Account of Aristotle’s Logic (1774)

* Joachim Georg Darjs (1714 – 1791)

** Logick, or the right use of reason (1725)

* Gottfriend Plocquet (1716 – 1790)

Teacher of Hegel. Developed squares to represent syllogisms.

** Fundamenta Philosophiae Speculativae (1759)

Used squares for logic diagrams

* Johann Heinrich Lambert (1728 – 1777)

Worked on creating an intensional calculus of logic in connection with the tree of Porphyry.

He introduced relative product which can be used to compose relations together to attain transitivity:
X ```is a friend of``` Y ```is a friend of``` Z giving X ```is a friend of``` of Z.

He also introduce ideas like newConcept = fn :: anotherConcept
where :: means a function fn applied to another concept. This is said to have possibly influenced Frege’s work.

** Sechs Versuche einer Zeichenkunst in der Vernunftlehre (1777)
Six Attempts at a Symbolic Method in the Theory of Reason

Intensional system with terms standing for concepts instead of individuals.

** Idea of genus and differentia

** Neues Organon oder Gedanken über die Erforschung und Bezeichnung des Wahren und dessen Unterscheidung vom Irrtum und Schein (1764)

Popularly known as Neues Organon

* Georg von Holland (1742 – 1784)

Took an extensional standpoint

* Johann Jakob Brucker

* Gottlob Benjamin Jäsche
Produced a compilation of logic lectures of Kant including the logical diagrams used

* Johann August Heinrich Ulrich
Used linear diagrams

* Gotthelf Samuel Steinbart
Used linear diagrams

* Johann Gebhardt Ehrenreich Maaß
Used triangles in his logic based on Lambert’s line diagrams

* Johann Gottfried Kiesewetter
Used circle diagrams to illustrate rules of conversion

* Georg Samuel Albert Mellin
Linked Kant’s The False Subtlety of the Four Syllogistic Figures with Euler’s and Lambert’s logic

* Heinrich Wilhelm Clemm

* Wilhelm Ludwig Gottlob von Eberstein

* Christian August Semler (1767 – 1825)

* John Gillies (historian) (1747 – 1836)

Translated Aristotle’s work and gave a nominalist defense of his logic.

* Joseph Diez Gergonne (1771 – 1859)

** Developed the method of Euler

* Immanuel Kant (1724 – 1804)

** Critique of Pure Reason

** The Mistaken Subtlety of the Four Syllogistic Figures (1762)

* Georg Wilhelm Friedrich Hegel (1770 – 1831)

** Science of Logic (1812 – 1816)

* Fitche

* Richard Kirwan (1733 – 1812)

** Logick (1807)

* Salomon Maimon (1753 – 1800)

* Bernhard Bolzano (1781 – 1848)

Wrote a Leibnizian nonsymbolic logic in 1837

** Paradoxien des Unendlichen (1851)

* August Detlev Twesten (1789 - 1876)

* Moritz Wilhelm Drobisch (1802 – 1896)

* Hermann Günther Grassmann (1809 – 1877)

** Ausdehnungslehre
Work on theory of extension

* Robert Grassmann (1815 – 1901)

Brother of Hermann Grassmann

** Die Begriffslehre oder Logik (1872)

* Friedrich Adolf Trendelenburg (1802 – 1872)

* Alois Riehl (1844 – 1924)

** Die englische Logik der Gegenwart (1876)
Introduced German speakers to the work of Boole, De Morgan, and Jevons

* English School of Logic

** Resources
*** [[https://amzn.to/3fltEvg][Handbook of the History of Logic – Volume 4: British Logic in the Nineteenth Century (2008)]]
*** [[https://amzn.to/303Wwlk][British Philosophy in the Seventeenth Century – Sarah Hutton (2015)]]
*** [[https://amzn.to/326dfH2][Language and Logic in the Post-Medieval Period – E. J. Ashworth (1974)]]
*** [[https://amzn.to/38RNFak][Logic and Rehtoric in England (1500-1700) – Wilbur Samuel Howell (1956)]]
*** [[https://amzn.to/3hiqBo0][Eighteenth Century British Logic and Rhetoric]]
*** [[https://amzn.to/2Ogb7Eu][Equations from God: Pure Mathematics and Victorian Faith (2007)]]
*** [[https://amzn.to/3joWjSi][Medieval aftermath: Oxford logic and logicians of the seventeenth century - I. Thomas (1964)]]
*** [[https://www.jstor.org/stable/23917977][The way of logic into mathematics]]
*** [[https://www.jstor.org/stable/421117][19th Century Logic between Philosophy and Mathematics – Volker Peckhaus (1999)]]

** The Barbershop Paradox / The Alice Problem

*** [[https://www.researchgate.net/profile/Amirouche_Moktefi/publication/280099042_Lewis_Carroll_and_the_British_nineteenth-century_logicians_on_the_barber_shop_problem/links/5773d06408ae1b18a7de37fd/Lewis-Carroll-and-the-British-nineteenth-century-logicians-on-the-barber-shop-problem.pdf][Lewis Carroll and the British nineteenth-century logicians on the barbershop problem]]

* Sir Wililam Hamilton (1730 – 1803)

* Richard Whately (1787 – 1863)

Whately’s work is said to have arose from the tradition of Henry Aldrich, Isaac Watts, and John Wesley.

** Elements of Logic (1826)
Credited by De Morgan as single handedly bringing about a revival in English school of logic

** Works on Whatley’s life

*** [[https://digitalcollections.dordt.edu/faculty_work/230/][Richard Whately and the Revival of Syllogistic Logic in Great Britain in the Early Nineteenth Century – Calvin Jongsma (1982)]]

* William Hamilton, 9th Baronet (1788 – 1856)

** Logic, in reference to the recent English treatises on that science (1833)
Available in [[https://archive.org/details/discussiononphil00hamiuoft][Discussions on Philosophy and literature (1861)]]

** Institutio logicae (1687)

* Dugald Stewart (1753 – 1828)

* Charles Babbage (1791 – 1871)

* George Bentham (1800 – 1884)

** Outline of a new system of logic, with a critical examination of Dr. Whately’s ‘Elements of Logic’ (1827)

* Ada Lovelace (1815 – 1852)

* Charles Graves (1812 – 1899)

* George Peacock (1791 – 1858)

* D.F. Gregory (1813 – 1844)

** [[https://www.cambridge.org/core/journals/earth-and-environmental-science-transactions-of-royal-society-of-edinburgh/article/xon-the-real-nature-of-symbolical-algebra/33822F167E8ECC7DFFEE2B01CA0F32F3][On the Real Nature of Symbolical Algebra – 1839]]

** Works on the life of Gregory

*** [[https://pdfs.semanticscholar.org/ff7a/89c1843e3876461ca910ff6f19377fbc6500.pdf][Symbolical Algebra as a Foundation for Calculus: D. F. Gregory’s Contribution]]

* George Boole (1815 – 1864)

[[Boole’s portrait from his 1865 obituary][./img/boole.png]]

[[https://archive.org/details/illustratedlondov46lond/page/60/mode/2up][Image source]]

First published work of Boole in mathematics was on analysis. Fellow of Trinity College in Cambridge called Gregory would help Boole to publish this paper in Transactions of The Cambridge Philosophical Society in 1844. This paper would go on to win the society’s gold medal thereby establishing Boole’s reputation. The paper is a work on calculus of operations.

Boole was inspired to take up work in logic after seeing a dispute between De Morgan and Hamilton in one of the periodicals. He would go on to apply this calculus of operators to logic, thereby algebraizing logic and creating the domain of algebra of logic.

Boole’s logic on deductive logic is but one half with inductive logic and probability theory being the other half of his works in 1847 and 1854.

TODO: Trace if these letters of dispute between De Morgan and Hamilton is available.

** [[https://archive.org/details/mathematicalanal01bool/page/n3/mode/2up][The mathematical analysis of logic (1847)]]

His first pamphlet was called a mathematical analysis of logic, that was published on 29th October, 1847. He first sent it to Rev. Charles Graves at the Cambridge University, who approved it and is said to make some ingenious additions.

TODO: Trace what these additions where.

A detailing of this work is available here: https://www.math.uwaterloo.ca/~snburris/htdocs/MAL.pdf

** [[https://babel.hathitrust.org/cgi/pt?id=mdp.39015030033925&view=1up&seq=195][The calculus of logic (1848)]]

** The Laws of Thought (1854)

** Works on Boole

*** [[https://academic.oup.com/mind/article-abstract/LVII/226/149/949579][Boole and the Revival of Logic – Kneale 1942]]

A good introduction into the life of George Boole.

*** [[https://royalsocietypublishing.org/doi/10.1098/rsnr.1956.0006][Boole and the Algebra of Logic – Kneale 1956]]

*** [[https://projecteuclid.org/download/pdf_1/euclid.rml/1204835162][The algebra of logic: What Boole really started (1994)]]

* Augustus De Morgan (1806 – 1871)

** Formal Logic; or, the Calculus of Inference, Necessary and Probable (1847)

** On the Syllogism (1868, Unpublished)

** On the foundation of algebra

** Works on De Morgan

*** [[https://sites.tufts.edu/histmath/files/2015/11/richards-demorgan.pdf][Augustus De Morgan, the History of Mathematics, and the Foundations of Algebra]]

* John Stuart Mill (1806 – 1873)

** A System of Logic (1843)

* Thomas Solly (1816 – 1875)

** A Syllabus of Logic (1839)

Presented an extensional logic

* Alexander Bain (1818 – 1903)

* Sophie Bryant (1850 – 1922)

* Emily Elizabeth Constance Jones (1848 – 1922)

* Arthur Thomas Shearman

** The Development of Symbolic Logic: A Critical-Historical Study of the Logical Calculus (1906)

* Logic of Relatives

* Lattice Theory

* James Joseph Sylvester (1814 – 1897)

** System of Logic (1843)

* William Stanley Jevons (1835 – 1882)

* John Venn (1834 – 1923)

* Richard Dedekind (1831 – 1916)

* Hugh MacColl (1831 – 1909)

- Created the first known variant of propositional calculus (Verify).
- Influenced C. I. Lewis in his modal logic.
- Explored pluralistic logical systems.
- Worked on the [[https://www.researchgate.net/publication/233139704_McColl_and_Minimization][minimization problem]]

** Works

*** [[https://www.jstor.org/stable/2248189][Linguistic Misunderstandings. Part I]]
Contains a section on Axioms, 

** Works on MacColl

*** [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.62.4830&rep=rep1&type=pdf][Hugh MacColl and the Tradition of Logic]]
*** [[https://journals.openedition.org/philosophiascientiae/351?lang=en][Hugh MacColl after One Hundred Years]]


* Lewis Carroll / Charles Dodgson (1832 – 1898)

** Symbolic Logic (1896)

* Charles Peirce (1839 – 1914)

Peirce tried to unite the algebraic logic of Boole and quantified relational inferences of De Morgan. Peirce moved away from equational logic and tried to bring a logic of relatives.

Peirce introduced quantifiers briefly in 1870.

* Logic of Relatives

* Ernst Schröder (1841 – 1902)

Schröder borrowed quantifiers from Peirces for his influential treatise on the algebra of logic which was adopted by Peano from Schröder.

** Der Operations-kreis des Logikkalkulus (1877)
Equational algebraic logic influenced by Boole and Grassmann

** Vorlesungen über die Algebra der Logik (1890 – 1905)

** Idea of logical domains (Gebiete)

** Idea of duality

* Works on Peirce

** [[https://core.ac.uk/download/pdf/82687196.pdf][Putnam on Peirce]]

** [[https://arisbe.sitehost.iu.edu/menu/library/aboutcsp/ANELLIS/views.pdf][Some views of Russell and Russell’s logic by his contemporaries, with particular reference to Peirce]]

* Georg Cantor (1845 – 1918)

Cantor was working with calculus and the attempt to formalize the idea of inifinitesimals and infinities lead to the creation of set theory formalism.
This helps with modelling logic when classes themselves have other classes inside them.

** Characteristic Function

* Planton Sergeevich Poretsky (1846 – 1907)

* O. H. Mitchell (1851 – 1889)

** [[https://www.jstor.org/stable/40320486?seq=1][The Life and Logical Contributions of O. H. Mitchell, Peirce’s Gifted Student]]

* Christine Ladd Franklin (1847 – 1930)

* Gottlob Frege (1848 – 1925)

** Begriffschrift (1879)

Introduced first-order predicate logic.

Predicates are described as functions, suggestive of the technique of Lambert.

** Grundgesetze der Arithmetik (1893–1903)

** Die Grundlagen der Arithmetik (1884)

* Louis Liard (1846 – 1917)

* John Cook Wilson (1849 – 1915)

* Felix Klein (1849 – 1925)

* Alfred Kempe (1849 – 1922)

** [[https://royalsocietypublishing.org/doi/pdf/10.1098/rstl.1886.0002][A memoir on the theory of mathematical form (1886)]]

** Note to a memoir on the theory of mathematical form (1887)

** On the relation between the logical theory of classes and the geometrical theory of points (1889)

** The subject matter of exact thought (1890)

** The theory of mathematical form: a correction and clarification (1897)

* Alexander Macfarlane (1851 – 1913)

* Josiah Royce (1855 – 1916)

** ∑ System
*** [[https://www.ams.org/journals/tran/1905-006-03/S0002-9947-1905-1500718-9/S0002-9947-1905-1500718-9.pdf][The Relation of the Principles of Logic to the Foundations of Geometry (1905)]]

* William Ernest Johnson (1858 – 1931)

* Allan Marquand (1853 – 1924)

* Henri Poincaré (1854 – 1912)

* Giuseppe Peano (1858 – 1932)

** Calcolo geometrico secondo l’Ausdehnungslehre di H. Grassman (1888)

** Peano postulates

* Alessandro Padoa (1868 – 1937)

* James Edwin Creighton (1861 – 1924)

* Cesare Burali-Forti (1861 – 1931)

** Burali-Forti paradox

* F. H. Bradley (1864 – 1924)

* Horace William Brindley Joseph (1867 – 1943)

* Louis Couturat (1868 – 1914)

** De l’Infini mathematique (1896)

** Algèbre de la logique (1905)

* Edward Huntington (1874 – 1952)

* Ralph Monroe Eaton (1892 – 1932)

* Lizzie Susan Stebbing (1885 – 1943)

* Daniel Sommer Robinson (1888 - 1977)

* V. V. Bobyin

* Brouwer

* David Hilbert (1862 – 1943)

** Epsilon Calculus

Shows the dynamical aspect of the meaning of quantifiers

** Recursive Schemes

* Finitary Mathematics

* Entscheidungsproblem

** First appeared in Grundzüge der theoretischen Logik (1928)

* Continuum Hypothesis

* Model Theory

An axiomatic system can be thought of as a system that describes a part of the world by employing a set of models.
These models can be thought of as interpretations of the system in which all the axioms are tautological.

A proposition specifies a class of models.

* Ackermann

* Rózsa Péter

* Paul Bernays (1888 - 1977)

* Quantification / Quotification

* Subjects

* Objects

* Properties of objects and relations between objects/properties

* Predicates

* Illative logic

* Quantifier free first order logic

* Logic with quantification over individuals

This is known in different names as:
** First order logic
** First order predicate logic
** Quantification theory
** Lower predicate calculus

* (Pure) Monadic Predicate Calculus
Term logic can be expressed as monadic predicate calculus.
It is completely decidable.

* Monadic second-order logic
Allows predicates of higher arity in formulas, but restricts second-order quantification to unary predicates.

* The problem of multiple generality

* Plurality of copula

In first order logic, to be is ambiguous. It can stand for:

** Predication
Tomato is red
IsRed(tomato)

** Identity

Tomato is pomodoro in Italian
tomato = pomodoro

** Existence

Tomato is / Tomato exists
ThereExists x : x = Tomato

** Class inclusion

Tomato is a fruit
ForAll(x) : Tomato(x) subsetOf Fruit(x)

First order logic cannot express all the concepts and modes of reasoning in mathematics such as:
- Equinumerosity / Equicardinality
- Infinity

* Quantification over higher order objects

* Primitive Recursive Arithmetic

* Finitary perspective
Hilbert’s Program

* Metamathematics

* Higher order logics

The distinction between logical systems in which quantification is allowed over higher-order entites and first order was accomplished largely by the efforts of David Hilbert and his associates. It is expounded in Grundzüge der Theoretischen Logik.

* Proof Theory

* Sheffer

** [[./refs/the-general-theory-of-notational-relativity.pdf][The General Theory of Notational Relativity]]

* Gerhard Gentzen (1909 – 1945)

** Sequent Calculus

** Consistency of arithmetic with certain nonfinitistic assumptions

* Kurt Gödel (1906 - 1978)

Gödel proved that the negation of continuum hypothesis cannot be proved in ZF set theory.

** Über formal unentscheidbare Satze der Principia Mathematica und verwandter Systeme (1931)

** Axiom of constructibility

** Constructible universe

** General Recursiveness

Functions that are effectively calculable are called general recursive

** Incompleteness theorems

It was assumed that descriptive completeness and deductive completeness coincide.
This was a central assumption in the metalogical project of proving the consistency of arithmetic.

* Neumann-Bernays-Gödel set theory

* Heyting

* Łukasiewcz

** Many valued logic

* Logicism

*** [[https://www.jstor.org/stable/27900598][Logistic and the Reduction of Mathematics to Logic]]
James Bymie Shaw, 1916

** Theory of Types

*** [[https://macsphere.mcmaster.ca/bitstream/11375/12315/1/fulltext.pdf][A History of the Theory of Types]]
Also, published as a book

* Computation

* Bertrand Russell

** Principia Mathematica

Used a higher order logic.
Intended to reduce arithmetic to logic.
Defined number of a class as the class of classes equinumerous with it.
A number as all the classes of objects with the same cardinality. This is quoted often as said by Quine.

Following arithmetization of analysis, a lot of mathematics was shown to be linked with arithmetic.

** Russell’s paradox

** Simple theory of types

** Vicious circle principle

** Ramified theory of types

** Axiom of reducibility

*** Works on Principia Mathematica

*** [[https://amzn.to/2WwNiwQ][The Evolution of Principia Mathematica]]
Bernard Linsky (2011)

* Ludwig Wittgenstein

* Alfred North Whitehead (1861 – 1947)

** A Treatise on Universal Algebra (1898)

* Oswald Veblen (1880 – 1960)
Founding member of Institute of Advanced Study

* Moses Schönfinkel (1889 – 1942)

* Frank Ramsey (1903 – 1930)

Showed how Principia Mathematica could be casted differently by taking a purely extensional view of higher order objects such as properties, relations, and classes.

* C. I. Lewis
Has written a survey on symbolic logic.

Proposed to extend classical logic with modalities.

* Emil Post (1897 – 1954)

** Functional completeness theorem
Article on completeness theorem: http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=16D208C94D8F16914F1921B765820E42?doi=10.1.1.89.2460&rep=rep1&type=pdf

** Post’s problem

* Degrees of unsolvability
** Equivalence classes of Turing reducibility

* Alonzo Church (1903 – 1995)

** Semantic completeness and resulting undecidability of first order logic

* Alan Turing (1912 – 1954)

* Andrey Andreyevich Markov Jr. (1903 – 1979)

* Paul Cohen (1934 – 2007)

Proved that continuum hypothesis cannot be proved in ZF.

* Effective Calculability

* Computability

** Recursive Functions

** Computable Functions

** Papers on the movement

** Decidability

* Diagonal lemma

* Stephen Cole Kleene (1909 – 1994)

** Three valued logic

* William Craig (1918 – 2016)

* Richard Friedberg (Born 1935)

* Andrey Muchnik (Born 1934 – 2019)

Contributed to the view of intuitionism as “calculus of problems”

Proved the lattice of Muchnik degrees is Brouwerian.

** Muchnik degrees

* Roger Lyndon (1917 – 1988)

* Barkley Rosser

* Lindenbaum

* Alfred Tarski (1901 – 1983)

Demonstrated that Boolean algebra without quantifiers were inadequate.

** The Concept of Truth in Formalized Languages (1933)

Introduced object language vs. metalanguage distinction

** [[https://www.academia.edu/12410865/Alfred_Tarskis_What_are_Logical_Notions_Edited_and_introduced_by_John_Corcoran_][What are the logical notions? (Lecture Delivered: 1966 / Published: 1986)]]

** [[https://www.dimap.ufrn.br/~jmarcos/papers/AoT-McKinsey_Tarski.pdf][The Algebra of Topology]]
Established connection between modal logic S4 and topological and metric spaces.

* Leon Henkin (1921 – 2006)

Presented an improved version of the completeness proof of first order logic

** Standard and nonstandard models of formal logic

Formalized the distinction that all classes can mean all classes that are composable of their members or all the classes definable in a given language.

* Rudolf Carnap (1891 – 1970)

Presented a systematic theory of semantics

** Logische Syntax der Sprache (1934)

** Introduction to Semantics (1942)

** Meaning and Necessity (1947)

* Rosenbloom

* Thoralf Skolem (1887 – 1963)

** Begründung Der Elementaren Arithmetik Durch Die Rekurrierende Denkweise Ohne Anwendung Scheinbarer Veranderlichen Mit Unendlichem Ausdehnungsbereich (1923)
** The development of recursive arithmetic (1946)

** Skolem functions

* Jean van Heijenoort (1912 – 1986)

** Distinction of logic as language vs. logic as calculus

* Meta Logic

* Consistency

* Satisfiability

As in Model Theory

* Completeness

** Descriptive completeness / Axiomatizability

** Semantical completeness

** Deductive Completeness

If a formal logic that the axiomatization uses is semantically complete, deductive completeness
usually coincides with descriptive completeness.

** Maximal completeness

If adding new elements to one of its models leads to a violation of the other axioms.

* Leopold Löwenheim (1878 – 1957)

* Abraham Robinson (1918 – 1974)

* Saul Kripke (1940 – Present)
Formulated relational semantics for modal logic.

- Frames
- Kripke Semantics

* Dov Gabbay

* Krister Segerberg

* Robert Goldblatt

* S. K. Thomason

* Henrik Sahlqvist

* Johan van Benthem

* Jacques Herbrand (1908 – 1931)

* Recursion Theory

* Freudenthal

* Infinitary logics

Encouraged the development of noncompositional truth definitions, initially formulated in terms of a selection game.

The paradigm of using games to define truth eventually lead to the development of game-theoretic semantics.

* Game semantics

* Carol Karp (1926 – 1972)

* Saharon Shelah (Born 1945)

* Stability Theory

* Williard Van Orman Quine

* Halmos

* Charles West Churchman (1913 – 2004)

* Bourbaki

* Samuel Eilenberg

* Saunders Mac Lane

* Lawvere

* Ernest Zermelo (1871 – 1953)

** Zermelo-Fraenkel set theory

A first order theory Eliminated comprehension principle and brought in construction of set using iterative method.

** Axiom of extensionality
Two sets are identical if they have the same members

** Axiom of elementary sets
There exists a set with no elements.
For any a and b, there exists sets with just a and be as their elements.

** Axiom of separation
A set can be partitioned based on the property it has.

** Power-set axiom
If S is a set, there is another set PowerSet(S) that contains all and only the subsets of S.

** Union axiom
If S is a set of sets, then there is another UnionOfChildren(S) which contains a set with all the elements of the subsets of S.

** Axiom of choice
If S is a non-empty set with mutually exclusive sets, then there is a set that contains pairs of members from each sets of S.

** Axiom of inifinity
There is at least one set that contains an infinity number of members.

* Abraham Fraenkel (1891 – 1965)

* John von Neumann (1903 – 1957)

** Foundation axiom

* Solomon Feferman (1928 – 2016)

* Belnap

** Four valued logic

* Cumulative Hierarchy

* Haskell Curry (1900 – 1982)

** Combinatory Calculus

* Dana Scott (1932)

** Denotational Semantics

* Paul Lorenzen (1915 – 1994)
Invented dialogical logic with Kuro Lorenz.
Influenced semantical tableaux method

* Kuno Lorenz (Born 1932)

* Evert W. Beth (1908 – 1964)

Introduced semantical tableux method in 1955.
Found out that Gentzen-type proofs could be interpreted as frustrated counter-model constructions.

* Jean-Yves Girard

* Samson Abramsky

* Johan van Bentham

* Hugo Steinhaus (1887 – 1972)

* Jan Mycielski (Born 1932)

** Axiom of determinateness

* Andreas Blass

* John Woods

* Yury Vladimirovich Matiyasevich (Born 1947)

* Julia Robinson (1919 – 1985)

* Martin Davis (Born 1928)

* Martin-Löf

A good reading list of Martin Löf’s papers is available [[https://github.com/michaelt/martin-lof][here]].

* Jaako Hintikka (1929 – 2015)

** Introduced independence-friendly first order logic

Lead to making equinumerosity, infinity, and truth being expressible in first-order language

* Else M. Barth

* Stewart Shapiro

** [[https://www.cambridge.org/core/journals/review-of-symbolic-logic/article/we-hold-these-truths-to-be-self-evident-but-what-do-we-mean-by-that/B494AB9D7C81EEAC48A9173EEE75D9A7][We hold these truths to be self-evident but what do we mean by that?]]

* John Reynolds

** [[http://www.cs.cmu.edu/afs/cs/user/jcr/ftp/][Papers by John Reynolds]]

* Notes

There seems to be a link between how Kempe influenced Peirce, both influenced Royce, which ends up influencing Sheffer in arriving at his “notational relativity” programme.

C. I. Lewis was the student of Royce, whose book Post reads and becomes an aid in formulating at his linguistic approach to logic to arrive at string rewriting systems.

Chomsky learns of Post’s work via Rosenbloom’s book.

* Surveys

** [[https://amzn.to/2N79N6q][A Survey of Symbolic Logic - C. I. Lewis]]

** [[https://amzn.to/2Ct4vQr][The Search for Mathematical Roots, 1870-1940 – I. Grattan-Guinness (2000)]]

** [[https://amzn.to/327EYXX][Medieval Logic An Outline of Its Development from 1250 to c. 1400 - Philotheus Boehner]]

** [[https://www.elsevier.com/books/book-series/handbook-of-the-history-of-logic][Handbook of Logic]]
A multivolume series with scholarship in the history of logic

** [[https://projecteuclid.org/euclid.rml/1204834850][Historical Development of Modern Logic - Jean van Heijenoort (1992)]]

** [[https://amzn.to/2BQsWHX][The Development of Logic — Kneale and Kneale (1985)]]

** [[https://amzn.to/3endvb5][Ancient Formal Logic (1951)]]
I. M. Bochenski

** La Logique de Théophraste (1947)
I. M. Bochenski

** Aristotle’s Syllogistic from the Point of View of Modern Formal Logic (1957)
J. Lukasiewicz

** [[10.3390/axioms9020056][Aristotle’s Syllogistic as a Deductive System (15 May 2020)]]
Piotr Kulicki

** Stoic Logic (1961)
B. Mates

** Aristotle’s Theory of the Syllogism (1968; G. orign 1959)
G. Patzig

** Ancient Logic and its Modern Interpretations (1974)
J. Corcoran (ed.)

** Die stoische Logik (1974)
Michael Frede

** Stoic vs. Aristotelian Syllogistic
Michael Frede

in Ancient Philosophy (1987)

** The Ancient Empiricists
Michael Frede

in Ancient Philosophy (1987)

** [[https://archive.org/details/philodemusonmeth00phil?view=theater][Philodemus on Methods of Inference (1977)]]
P. H. and E. A. De Lacy

** Les Stoiciens et leur logic (1978)
J. Brunschwig

** The Origins of Non-deductive Inference
M. Burnyeat

in Science and Speculation (1982)

** On Signs
D. Sedley
in Science and Speculation (1982) by J. Barnes and others (eds.)

** [[https://www.amazon.com/griechische-Tradition-aristotelischen-Syllogistik-Spa%CC%88tantike/dp/3525251777][Die griechische Tradition der aristotelischen Syllogistk in der Spätantike (1984)]]
T. S. Lee

** Die Fragmente zur Dialektik der Stoiker (1987-8)
Karlheinz Hülser

** Theophrastus of Eresus: Sources for his Life, Writings, Thought and Influence
P. M. Huby

** [[https://amzn.to/3d3r8cu][Elements of Symbolic Logic (1947)]]
Hans Reichenbach

** [[DigitizedbytheInternetArchivein2011withfundingfromLyrasisMembersandSloanFoundationhttp://www.archive.org/details/historyofformallOOboch][History of Formal Logic]]
I. M. Bochenski

Originally published as: Formale Logik

** [[http://www.columbia.edu/%7Eav72/papers/JANCL_2003.pdf][The Geometry of Negation]]
Negation as a rotation of polygons/polyhedra. Also gives a brief survey of different kinds of logic systems and the kind of group actions implicit in their structures.

** [[https://research-repository.st-andrews.ac.uk/handle/10023/16114][Descartes critique of the syllogistic]]

** [[https://www.semanticscholar.org/paper/Negating-as-turning-upside-down-Skowron-Kubi's/0ef270e35018919a2dcdd3fc84263e37504cee7b][Negation as turning upside down]]

Links logic with category theory and adjointness

** [[https://www.springer.com/gp/book/9783034874045][Russel and the Origins of the Set-Theoretic ‘paradoxes’]]

** [[https://www.academia.edu/1145206/Entry_Logic_in_the_Oxford_Classical_Dictionary_Very_brief_][Entry Logic in Oxford Dictionary]]

** [[https://www.jstor.org/stable/301542][The Formation of Modern Conceptions of Formal Logic in the Development of Geometry (1939)]]
Ernest Nagel

** [[Impossible Numbers]]
Ernest Nagel (1935)

** [[https://www.maa.org/press/periodicals/convergence/math-origins-the-logical-ideas][Math Origins: The Logical Ideas]]

** [[https://mitpress.mit.edu/books/history-mathematical-logic-leibniz-peano][History of Mathematical Logic from Leibniz to Peano]]
A book released in Russia where it interprets the old work in medieval logic and interprets it in the light of modern logical concepts.

** [[https://amzn.to/2OKEfUB][From Frege to Gödel]]

A sourcebook which contains a curation of the significant papers that influenced the course of history of logic.

** [[https://philpapers.org/archive/FINGAR-2.pdf][Greek and Roman Logic Survey - Oxford Bibliographies]]

** [[https://amzn.to/2Gw2tBE][The Development of Modern Logic]]
Leila Haaparanta

** [[https://amzn.to/2ONswVu][The Historic Development of Logic (1929) – Federigo Enriques]]

** [[https://archive.org/details/historicalsketch00blak/page/n17/mode/2up][Historical Sketch of Logic, from the Earliest Time to the Present Day]]

** [[https://archive.org/details/concisehistoryof00scho/][Concise history of logic - Heinrich Scholz]]

** [[https://archive.org/details/systemlogicandh01lindgoog/page/n8/mode/2up][Systems of logic and history of logical doctrines - Freidrich Ueberweg (1871)]]

** [[https://amzn.to/3az87io][Medieval Logic and Metaphysics (1972)]]
D. P. Henry

** Historisches Wörterbuch der Philosophie

** Introduction to Logic
William of Sherwood

** Logica Parva
Paul of Venice

** Philosophisches  Bibliothek
Publisher: Felix Meiner Verlag

** Epistemic Logic in the Later Middle Ages (1993)
Ivan Boh

** Realizing Reason: A Narrative of Truth and Knowing
D. Macbeth (2014)

** H.E. Allison (1973)
The Kant-Eberhard-Controversy

** Logische Studien: Ein Beitrag zur Neubegründung der formalen Logik und der Erkenntnistheorie
F. A. Lange (1894)

** Institutiones logicæ
I. Denzinger (1824)

** Lectures on Metaphysics and Logic
Hamilton, W. (1860)
Documents the work of Alsted on logical diagrams

Contains details on the work of Vives

** Reformversuche protestantischer Metaphysik im Zeitalter des Rationalismus
Leinsle U. G. (1988)

** De calculo logico
Drobisch, M. W. (1827)

** System der Logik und Geschichte der logischen Lehren
Ueberweg, F. (1857)

** Logik, Mathesis universalis und allgemeine Wissenschaft: Leibniz und die Wiederentdeckung der formalen Logik
Peckhaus, V. (1997)

** Erhard Weigel’s Contributions to the Formation of Symbolic Logic (2013)
Bullynck, M.

** Kant’s Conception of Logical Extension and Its Implications
H. Lu-Adler (2012)

** Cross-Examining Propositional Calculus and Set Operations
Randolph, J.F. 1965

** Der junge Leibniz I: Die wissenschaftstheoretische Problemstellung seines ersten Systementwurfs (1978)
Moll, K.

** Die Quantität des Inhalts: Zu Leibnizens Erfassung des Intensionsbegriffs durch Kalküle und Diagramme (1979)
Thiel, C.

** Leibnizens Synthese von Universalmathematik und Individualmetaphysik
Mahnke, D. 1925

** Handschriftlicher Nachlaß. Philosophische Vorlesungen. Erste Hälfte. Theorie des Erkennens
Schopenhauer 1913

** System der Logik und Geschichte der logischen Lehren
Ueberweg 1857

** Johann Christoph Sturm und Gottfried Wilhelm Leibniz (2004)
Kratochwil, S.

** Idea Matheseos universe cum speciminibus Inventionum Mathematicarum (1669)
E. VVeigelus

** Neu-erfundener Hauß-Rath/ so wohl zur Nothdurfft/ als zur Lust und Bequemligkeit/zu gebrauchen
E. Weigelius

** Grundprobleme der Logik. Elemente einer Kritik der formalen Vernunft
Stekeler-Weithofer 1986

** Music Theory and Mathematics
Nolan 2002

** Embodiments of Will. Anatomical and Physiological Theories of Voluntary Animal Motion from Greek Antiquity to the Latin Middle Ages, 400 B.C.–A.D. 1300
Frampton, M. 2008

** On the employment of geometrical diagrams for the sensible representation of logical propositions
Venn, J. 1880

** Sur l’histoire des diagrammes logiques, ‘figures géométriques
E. Coumet 1977

* Historians

** William Calvert Kleene
** I. Grattan Guinness
** P. E. B Jourdain
